name: GitHub Actions Demo
run-name: ${{ github.actor }} vient de push, tests en cours
on: [push]
jobs:
  Install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6 # or alternative dependency management
      - run: make install
  Tests:
    runs-on: ubuntu-latest
    steps:
      - run: make test
