name: GitHub Actions Demo
run-name: ${{ github.actor }} vient de push, tests en cours
on: [push]
jobs:
  Install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6 # or alternative dependency management
      - run: sudo make install
  Tests:
    needs: Install
    runs-on: ubuntu-latest
    steps:
      - uses: php-actions/phpunit@v3
        with:
          configuration: "phpunit.xml"
      - run: XDEBUG_MODE=coverage ./vendor/bin/phpunit –coverage-text=coverage_test.txt
      #- run: make test
