name: GitHub Actions Demo
run-name: ${{ github.actor }} vient de push, tests en cours
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6 # or alternative dependency management
  
      - name: install dependencies
      - run: sudo make install

      - name: run tests
      - run: make test
